name: splitup_application
description: "An application for splitting up costs and managing expenses with friends."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: 3.29.0

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  google_sign_in: ^6.0.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.1.0
  firebase_storage: ^12.4.5
  csv: ^6.0.0
  path: ^1.9.0
  firebase_core: ^3.13.0
  provider: ^6.0.0
  flutterfire_cli: ^1.2.0
  flutter_native_splash: ^2.4.6
  image_picker: ^1.1.2
  g_recaptcha_v3: ^1.0.0
  intl: ^0.18.1
  syncfusion_flutter_xlsio: ^28.2.12
  file_picker: ^10.1.2
  path_provider: ^2.1.5
  flutter_svg: ^2.0.10
  flutter_web_auth_2: ^4.1.0
  firebase_analytics: ^11.4.5
  firebase_app_check: ^0.3.2+5
  fl_chart: ^1.0.0
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.4
  animations: ^2.0.11

dev_dependencies:
  fake_cloud_firestore: ^3.1.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  test: any
  build_runner: ^2.4.9
  mockito: ^5.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/logo/logo-header.png
    - assets/icon/splitup-logo.png
    - assets/introduction_animation/screen1.png
    - assets/introduction_animation/screen2.png
    - assets/introduction_animation/screen3.png
    - assets/introduction_animation/screen4.png
    - assets/introduction_animation/screen5.png

flutter_icons:
    android: true
    ios: true
    image_path: "assets/icon/icon.png"