name: Build and Deploy Flutter Web to Firebase Hosting

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove Flutter cache
        run: rm -rf "$HOME/.flutter"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: Install FlutterFire CLI
        run: dart pub global activate flutterfire_cli

      - name: Generate firebase_options.dart
        run: flutterfire configure --project=splitup-5972d --out=lib/config/firebase_options.dart --yes

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPLITUP_5972D }}"
          channelId: live
          projectId: splitup-5972d
